steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
      'build',
      '-t', '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/simulator:latest',
      '-f', 'Dockerfile.simulator',
      '.'
    ]
images:
- '${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO_NAME}/simulator:latest'
substitutions:
  _REGION: 'us-central1'
  _REPO_NAME: 'agentic-trading'